AllCops:
  Exclude:
    - vendor/**
    - .kitchen/**

ClassLength:
  Enabled: false
CyclomaticComplexity:
  Max: 15
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
TrailingComma:
  Enabled: false

AssignmentInCondition:
  Enabled: false
ParameterLists:
  Enabled: false

Style/FileName:
  Enabled: false
RegexpLiteral:
  Exclude:
    - '**/Guardfile'
